use e_navigator_signals::{
    CgroupCpuObservation, CgroupFileDescriptorObservation, CgroupMemoryObservation,
    CgroupPidsObservation, CgroupResourceContext, ContainerContext, KubernetesContext,
    MetricAggregationWindow, NodeCpuObservation, NodeDiskIoObservation, NodeFilesystemObservation,
    NodeLoadObservation, NodeMemoryObservation, ProcessResourceContext, ProcessResourceObservation,
    SignalEnvelope,
};

pub(super) fn signals(
    host: Option<String>,
    container: ContainerContext,
    kubernetes: KubernetesContext,
    started: u64,
) -> Vec<SignalEnvelope> {
    let window = MetricAggregationWindow {
        start_unix_nanos: started,
        end_unix_nanos: started.saturating_add(1_000),
    };
    let cgroup = CgroupResourceContext {
        cgroup_path: "/kubepods.slice/pod-synthetic/e-navigator.scope".to_string(),
        container: Some(container.clone()),
        kubernetes: Some(kubernetes.clone()),
    };
    let process = ProcessResourceContext {
        pid: std::process::id(),
        ppid: None,
        uid: None,
        command: "synthetic-api".to_string(),
        executable: Some("/app/synthetic-api".to_string()),
        container: Some(container.clone()),
        kubernetes: Some(kubernetes.clone()),
    };

    vec![
        SignalEnvelope::node_cpu_observation(
            super::source_name(),
            host.clone(),
            NodeCpuObservation {
                metric_name: "system.cpu.time".to_string(),
                unit: "ns".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                user_nanos: 1_000_000_000,
                system_nanos: 500_000_000,
                idle_nanos: 8_000_000_000,
                iowait_nanos: 100_000_000,
                steal_nanos: 0,
                runnable_tasks: Some(2),
                blocked_tasks: Some(0),
            },
        ),
        SignalEnvelope::node_cpu_observation(
            super::source_name(),
            host.clone(),
            NodeCpuObservation {
                metric_name: "system.cpu.time".to_string(),
                unit: "ns".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos.saturating_add(1_000),
                window: MetricAggregationWindow {
                    start_unix_nanos: window.end_unix_nanos,
                    end_unix_nanos: window.end_unix_nanos.saturating_add(1_000),
                },
                user_nanos: 1_030_000_000,
                system_nanos: 520_000_000,
                idle_nanos: 8_040_000_000,
                iowait_nanos: 100_000_000,
                steal_nanos: 0,
                runnable_tasks: Some(2),
                blocked_tasks: Some(0),
            },
        ),
        SignalEnvelope::node_memory_observation(
            super::source_name(),
            host.clone(),
            NodeMemoryObservation {
                metric_name: "system.memory.usage".to_string(),
                unit: "By".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                mem_total_bytes: 8 * 1024 * 1024 * 1024,
                mem_available_bytes: Some(5 * 1024 * 1024 * 1024),
                mem_free_bytes: Some(4 * 1024 * 1024 * 1024),
                swap_total_bytes: Some(1024 * 1024 * 1024),
                swap_free_bytes: Some(1024 * 1024 * 1024),
            },
        ),
        SignalEnvelope::node_load_observation(
            super::source_name(),
            host.clone(),
            NodeLoadObservation {
                metric_name: "system.cpu.load_average.1m".to_string(),
                unit: "1".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                load1: 0.25,
                load5: 0.5,
                load15: 0.75,
                runnable_tasks: Some(2),
                total_tasks: Some(200),
            },
        ),
        SignalEnvelope::node_filesystem_observation(
            super::source_name(),
            host.clone(),
            NodeFilesystemObservation {
                metric_name: "system.filesystem.usage".to_string(),
                unit: "By".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                mount_point: "/var/lib/kubelet".to_string(),
                filesystem_type: Some("synthetic".to_string()),
                total_bytes: 100 * 1024 * 1024 * 1024,
                available_bytes: 60 * 1024 * 1024 * 1024,
            },
        ),
        SignalEnvelope::node_disk_io_observation(
            super::source_name(),
            host.clone(),
            NodeDiskIoObservation {
                metric_name: "system.disk.io".to_string(),
                unit: "By".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                device: "synthetic0".to_string(),
                reads_completed: 10,
                writes_completed: 20,
                read_bytes: 4096,
                written_bytes: 8192,
            },
        ),
        SignalEnvelope::node_disk_io_observation(
            super::source_name(),
            host.clone(),
            NodeDiskIoObservation {
                metric_name: "system.disk.io".to_string(),
                unit: "By".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos.saturating_add(1_000),
                window: MetricAggregationWindow {
                    start_unix_nanos: window.end_unix_nanos,
                    end_unix_nanos: window.end_unix_nanos.saturating_add(1_000),
                },
                device: "synthetic0".to_string(),
                reads_completed: 12,
                writes_completed: 23,
                read_bytes: 8192,
                written_bytes: 16_384,
            },
        ),
        SignalEnvelope::process_resource_observation(
            super::source_name(),
            host.clone(),
            ProcessResourceObservation {
                metric_name: "process.resource".to_string(),
                unit: "1".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                process,
                cpu_time_nanos: Some(10_000_000),
                memory_rss_bytes: Some(64 * 1024 * 1024),
                virtual_memory_bytes: Some(128 * 1024 * 1024),
                open_fds: Some(32),
                socket_count: Some(4),
                thread_count: Some(8),
            },
        ),
        SignalEnvelope::cgroup_cpu_observation(
            super::source_name(),
            host.clone(),
            CgroupCpuObservation {
                metric_name: "container.cpu.time".to_string(),
                unit: "ns".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                cgroup: cgroup.clone(),
                usage_nanos: Some(2_000_000_000),
                user_nanos: Some(1_500_000_000),
                system_nanos: Some(500_000_000),
                throttled_periods: Some(0),
                throttled_nanos: Some(0),
            },
        ),
        SignalEnvelope::cgroup_cpu_observation(
            super::source_name(),
            host.clone(),
            CgroupCpuObservation {
                metric_name: "container.cpu.time".to_string(),
                unit: "ns".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos.saturating_add(1_000),
                window: MetricAggregationWindow {
                    start_unix_nanos: window.end_unix_nanos,
                    end_unix_nanos: window.end_unix_nanos.saturating_add(1_000),
                },
                cgroup: cgroup.clone(),
                usage_nanos: Some(2_060_000_000),
                user_nanos: Some(1_550_000_000),
                system_nanos: Some(510_000_000),
                throttled_periods: Some(0),
                throttled_nanos: Some(0),
            },
        ),
        SignalEnvelope::cgroup_memory_observation(
            super::source_name(),
            host.clone(),
            CgroupMemoryObservation {
                metric_name: "container.memory.usage".to_string(),
                unit: "By".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                cgroup: cgroup.clone(),
                current_bytes: Some(128 * 1024 * 1024),
                peak_bytes: Some(160 * 1024 * 1024),
                max_bytes: Some(512 * 1024 * 1024),
            },
        ),
        SignalEnvelope::cgroup_pids_observation(
            super::source_name(),
            host.clone(),
            CgroupPidsObservation {
                metric_name: "container.process.count".to_string(),
                unit: "{process}".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window: window.clone(),
                cgroup: cgroup.clone(),
                process_count: Some(3),
                thread_count: Some(12),
                max_processes: Some(512),
            },
        ),
        SignalEnvelope::cgroup_file_descriptor_observation(
            super::source_name(),
            host,
            CgroupFileDescriptorObservation {
                metric_name: "container.file_descriptor.count".to_string(),
                unit: "{file_descriptor}".to_string(),
                timestamp_unix_nanos: window.end_unix_nanos,
                window,
                cgroup,
                open_fds: Some(64),
                socket_count: Some(6),
            },
        ),
    ]
}
