apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "e-navigator.configMapName" . }}
  namespace: {{ include "e-navigator.namespace" . }}
  labels:
    {{- include "e-navigator.labels" . | nindent 4 }}
data:
  e-navigator.toml: |
    {{- .Values.config.toml | nindent 4 }}
