{{- if and .Values.serviceMonitor.enabled .Values.service.enabled .Values.prometheusHttp.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "e-navigator.fullname" . }}
  namespace: {{ include "e-navigator.namespace" . }}
  labels:
    {{- include "e-navigator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "e-navigator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
