[package]
name = "e-navigator-protocol"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
e-navigator-context-propagation = { path = "../e-navigator-context-propagation" }
e-navigator-signals = { path = "../e-navigator-signals" }
flate2 = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
