apiVersion: v2
name: e-navigator
description: Rust and eBPF signal plane for Linux and Kubernetes observability
type: application
version: 0.3.0
appVersion: "0.3.0"
home: https://github.com/guaracloud/e-navigator
icon: https://guaracloud.github.io/e-navigator/logos/logo-square-transparent.png
sources:
  - https://github.com/guaracloud/e-navigator
keywords:
  - ebpf
  - observability
  - profiling
  - kubernetes
