apiVersion: v1
kind: ServiceAccount
metadata:
  name: e-navigator
  namespace: e-navigator-system
  labels:
    app.kubernetes.io/name: e-navigator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e-navigator
  labels:
    app.kubernetes.io/name: e-navigator
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e-navigator
  labels:
    app.kubernetes.io/name: e-navigator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: e-navigator
subjects:
  - kind: ServiceAccount
    name: e-navigator
    namespace: e-navigator-system
